name: flutter_learn2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/launch.png"
  min_sdk_android: 21 # android min sdk min:16, default 2

flutter:
  uses-material-design: true
  assets:
  - images/

